services:
  postgres:
    image: postgres:16
    container_name: cimet-postgres
    environment:
      POSTGRES_DB: cimet_qa
      POSTGRES_USER: cimet
      POSTGRES_PASSWORD: cimet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
